#!/bin/bash
<<COMMENT
	PROGRAM:     grippeteer
	AUTHOR:      Frankie Baffa <frankiebaffa@gmail.com>
	DESCRIPTION: converts a github-flavored-markdown file to a github-styled
	             html page followed by a formatted PDF.
	LAST EDIT:   2021-03-08
COMMENT
# Setting IFS to "" to preserve line breaks and tabs during the stripping loop
# broke font awesome integration. Storing the default value here allows the
# reset of IFS before font-awesome replacement.
DEF_IFS=$IFS;
startunixtime="$(date +"%s")";
verbose="0";
log="0";
logfile="";
logstr="";
function savelogfile() {
	if [[ $verbose == "1" && $log == "1" && ! -z "$logfile" && ! -z "$logstr" ]]
	then
		printer "Saving log file \"$logfile\".";
		echo -ne "$logstr" > "$logfile";
	fi
}
function logtofile() { # $msg
	d="$1";
	msg="$2";
	if [[ $verbose == "1" && "$log" == "1" && ! -z "$logfile" && ! -z "$msg" ]]
	then
		logstr+="$d $msg\n";
	fi
}
function logprint() { # $msg
	msg="$1";
	d="$(date +"%Y-%m-%d %H:%M:%S.%N")";
	if [[ "$verbose" == "1" && "$log" == "1" && -z "$logfile" && ! -z "$msg" ]]
	then
		echo "$d $msg";
	elif [[ "$verbose" == "1" && "$log" == "1" && ! -z "$logfile" && ! -z "$msg" ]]
	then
		logtofile "$d" "$msg";
	fi
}
function verboseprint() { # $msg
	msg="$1";
	if [[ "$log" == "0" && ! -z "$msg" ]]
	then
		echo "$msg";
	elif [[ "$log" == "1" && ! -z "$msg" ]]
	then
		logprint "$msg";
	fi
}
function printer() { # $msg
	msg="$1";
	if [[ "$verbose" == "1" && ! -z "$msg" ]]
	then
		verboseprint "$msg";
	fi
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )";
STATIC="$DIR/.grippeteer";
HELP="$(<$STATIC/readme.txt)";

grip_check="$(command -v grip)";
GRIP="$(<$STATIC/grip.txt)";
if [[ -z "$grip_check" ]]
then
	echo "$GRIP";
	exit;
fi

puppeteer_check="$(command -v puppeteer-pdf)";
PUPPETEER="$(<$STATIC/puppeteer.txt)";
if [[ -z "$puppeteer_check" ]]
then
	echo "$PUPPETEER";
	exit;
fi

filename="";
getfilename="0";
force="0";
debug_html="0";
debug_grip_html="0";
getlogfile="0";
args="$(argbreaker "$@")";
for arg in ${args[@]}
do
	if [[ "$getfilename" == "0" && "$getlogfile" == "0" ]]
	then
		if [[ "$arg" == "-h" || "$arg" == "--help" ]]
		then
			echo "$HELP";
			exit 0;
		elif [[ "$arg" == "-F" || "$arg" == "--filename" ]]
		then
			getfilename="1";
		elif [[ "$arg" == "-f" || "$arg" == "--force" ]]
		then
			force="1";
		elif [[ "$arg" == "-d" || "$arg" == "--debug-html" ]]
		then
			debug_html="1";
		elif [[ "$arg" == "-v" || "$arg" == "--verbose" ]]
		then
			verbose="1";
		elif [[ "$arg" == "-g" || "$arg" == "--log" ]]
		then
			log="1";
		elif [[ "$arg" == "-L" || "$arg" == "--logfile" ]]
		then
			getlogfile="1";
		elif [[ "$arg" == "-G" || "$arg" == "--debug-grip-html" ]]
		then
			debug_grip_html="1";
		else
			printer "Unrecognized argument $arg";
			exit;
		fi
	elif [[ "$getfilename" == "1" ]]
	then
		filename="$arg";
		getfilename="0";
	elif [[ "$getlogfile" == "1" ]]
	then
		logfile="$arg";
		getlogfile="0";
	fi
done
if [[ -z "$filename" ]]
then
	printer "Missing value for filename";
	exit;
fi

if [[ ! -f "$filename.md" && ! -f "$filename.markdown" ]]
then
	printer "Input file does not exist."
	exit;
fi
inputfile="";
if [[ -f "$filename.md" ]]
then
	inputfile="$filename.md";
elif [[ -f "$filename.markdown" ]]
then
	inputfile="$filename.markdown";
fi

if [[ -f "$filename.html" && "$force" == "0" ]]
then
	printer "File \"$filename.html\" would be overwritten then deleted.";
	exit;
elif [[ -f "$filename.html" && "$force" == "1" && "$debug_html" == "1" ]]
then
	printer "File \"$filename.html\" will be overwritten.";
elif [[ -f "$filename.html" && "$force" == "1" && "$debug_html" == "0" ]]
then
	printer "File \"$filename.html\" will be overwritten and deleted.";
fi

if [[ -f "$filename.pdf" && "$force" == "0" ]]
then
	printer "File \"$filename.pdf\" would be overwritten.";
	exit;
elif [[ -f "$filename.pdf" && "$force" == "1" ]]
then
	printer "File \"$filename.pdf\" will be overwritten.";
fi

printer "Running grip.";
grip_html="$(grip --user="$GIT_USER" --pass="$GIT_PASS" "$inputfile" --export -)";
# check if grip debug file exists, force is off, and debug_grip_html is on
if [[ -f "$filename.grip.html" && "$force" == "0" && "$debug_grip_html" == "1" ]]
then
	printer "File \"$filename.grip.html\" would be overwritten.";
	exit;
# check if grip debug file exists, force is on, and debug_grip_html is on
elif [[ -f "$filename.grip.html" && "$force" == "1" && "$debug_grip_html" == "1" ]]
then
	printer "File \"$filename.grip.html\" will be overwritten.";
fi
# check if force is on and debug_grip_html is on
if [[ "$force" == "1" && "$debug_grip_html" == "1" ]]
then
	printer "Exporting raw grip html to \"$filename.grip.html\"";
	echo "$grip_html" > "$filename.grip.html";
fi

printer "Removing line breaks while preserving code tags";
html="";
opened_pre_tags=0;
closed_pre_tags=0;
IFS=''
while read data
do
	line=$data;
	opened_this_line=$(echo "$line" | grep -c "<pre>");
	opened_pre_tags=$(($opened_pre_tags+$opened_this_line));
	closed_this_line=$(echo "$line" | grep -c "</pre>");
	closed_pre_tags=$(($closed_pre_tags+$closed_this_line));
	if [[ $opened_pre_tags > $closed_pre_tags ]]
	then
		html+="$line"$'\n';
	else
		html+="$line"$' ';
	fi
done <<< "$grip_html"
printer "Injecting style.";
html+="<style>$(<$DIR/.grippeteer/style.css)</style>";

printer "Injecting font awesome.";
# insert font awesome after head
fonta="s/<\/head>/<script src=\"https:\/\/kit.fontawesome.com\/66d3b9dbe0.js\" crossorigin=\"anonymous\"><\/script><\/head>/g";
html="$(echo "$html" | sed "$fonta")";

printer "Replacing \"# [[pagebreak]]\" with actual breaking div.";
# handle page break
# break represented by "# [[pagebreak]]" on a line by iteself
matchbreak="s/<h1> <a id=\"user-content-pagebreak[0-9\-]*\" class=\"anchor\" href=\"#pagebreak[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[pagebreak\]\]<\/h1>/<div style=\"page-break-after:always!important;\"><\/div>/g";
html="$(echo "$html" | sed "$matchbreak")";

printer "Replacing \"# [[doublestart]]\" with table beginning.";
matchtstart="s/<h1> <a id=\"user-content-doublestart[0-9\-]*\" class=\"anchor\" href=\"#doublestart[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[doublestart\]\]<\/h1>/<table class=\"tablesplit\"><tbody><tr><td class=\"tablecell\">/g";
html="$(echo "$html" | sed "$matchtstart")";

printer "Replacing \"# [[doublesplit]]\" with column split.";
matchtsplit="s/<h1> <a id=\"user-content-doublesplit[0-9\-]*\" class=\"anchor\" href=\"#doublesplit[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[doublesplit\]\]<\/h1>/<\/td><td class=\"tablecell\">/g";
html="$(echo "$html" | sed "$matchtsplit")";

printer "Replacing \"# [[doubleend]]\" with table beginning.";
matchtend="s/<h1> <a id=\"user-content-doubleend[0-9\-]*\" class=\"anchor\" href=\"#doubleend[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[doubleend\]\]<\/h1>/<\/td><\/tr><\/tbody><\/table>/g";
html="$(echo "$html" | sed "$matchtend")";

printer "Replacing \"# [[triplestart]]\" with table beginning.";
triplestart="s/<h1> <a id=\"user-content-triplestart[0-9\-]*\" class=\"anchor\" href=\"#triplestart[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[triplestart\]\]<\/h1>/<table class=\"triplesplit\"><tbody><tr><td class=\"tablecell\">/g";
html="$(echo "$html" | sed "$triplestart")";

printer "Replacing \"# [[triplesplit]]\" with column split.";
triplesplit="s/<h1> <a id=\"user-content-triplesplit[0-9\-]*\" class=\"anchor\" href=\"#triplesplit[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[triplesplit\]\]<\/h1>/<\/td><td class=\"tablecell\">/g";
html="$(echo "$html" | sed "$triplesplit")";

printer "Replacing \"# [[tripleend]]\" with triple beginning.";
tripleend="s/<h1> <a id=\"user-content-tripleend[0-9\-]*\" class=\"anchor\" href=\"#tripleend[0-9\-]*\" aria-hidden=\"true\"><span aria-hidden=\"true\" class=\"octicon octicon-link\"><\/span><\/a>\[\[tripleend\]\]<\/h1>/<\/td><\/tr><\/tbody><\/table>/g";
html="$(echo "$html" | sed "$tripleend")";

printer "Replacing //small// inline with small tag.";
# handle custom small tag
# tag represented by "//small//" inline to open and "//-small//" inline to close
small_open="s/\/\/small\/\//<small>/g";
small_close="s/\/\/-small\/\//<\/small>/g";
html="$(echo "$html" | sed "$small_open")";
html="$(echo "$html" | sed "$small_close")";

printer "Replacing //fas...// inline with font awesome tags.";
# handle font-awesome tags
# set IFS back to default value
IFS=$DEF_IFS;
fas=($(echo "$html" | grep -o '//fas [a-zA-Z0-9\-]\+//'))
for ((i = 0; i < "${#fas[@]}"; i+=2))
do
	fa="${fas[$i]} ${fas[(($i+1))]}"
	len=${#fa};
	fa="$(echo ${fa:2:(($len-4))})"
	fa_end="";
	replace="s/\/\/$fa\/\//<span class=\"$fa\"><\/span>/g";
	html="$(echo "$html" | sed "$replace")";
done;

printer "Adding \"target='_blank'\" to anchor tags.";
#links="s/<a /<a target=\"_blank\" /g";
html+="
<script>
Array.from(document.querySelectorAll('a')).forEach(elem => {
	var href = elem.getAttribute('href');
	if (href.substring(0, 1) !== '#') {
		elem.setAttribute('target', '_blank');
	}
});
</script>
";
html="$(echo "$html" | sed "$links")";
html+="
<script>
Array.from(document.querySelectorAll('h1,h2,h3,h4,h5,h6')).forEach(elem => {
	elem.id = elem.textContent.trim().toLowerCase().replaceAll(' ', '-');
});
</script>
";

printer "Exporting html to $filename.html.";
echo "$html" > "$filename.html";

printer "Running puppeteer-pdf for input $filename.html and output $filename.og.pdf.";
M="0.25in";
puppeteer-pdf \
	"$filename.html" \
	--path "$filename.og.pdf" \
	--marginTop="$M" \
	--marginBottom="$M" \
	--marginLeft="$M" \
	--marginRight="$M" \
	--format="Letter" \
	--printBackground;

if [[ "$debug_html" == "0" ]]
then
	printer "Deleting $filename.html.";
fi
if [[ "$debug_html" == "0" ]]
then
	rm "$filename.html";
fi

printer "Compressing pdf.";
# compress pdf
pdf_compress "$filename.og.pdf" "$filename.pdf"

printer "Removing uncompressed pdf $filename.og.pdf.";
# delete og
rm "$filename.og.pdf";

printer "Success.";
endunixtime="$(date +"%s")";
printer "Finished in $(($endunixtime-$startunixtime)) seconds.";
savelogfile;

